### ISSUE TITLE
CovenantRandomizer does not work with dev branch of covenant

### ISSUE THREAD

**Issue by hawaii883** [assume-breach/Home-Grown-Red-Team#1]
The script is great but i could not make it work with the dev branch although i changed the directories but could not create launcher anyway.

**Comment by assume-breach** [comment]
I've never tried to pull the dev branch. I always used RastaMouses fork from Zero Point Security because it has more features. Did you change URL from the Zero Point Security fork to the Dev branch directly in the script?

**Comment by assume-breach** [comment]
Post your error and I will take a look.

**Comment by assume-breach** [comment]
Closing issue.
