### ISSUE TITLE
Having Issues with Harriet

### ISSUE THREAD

**Issue by calex80** [assume-breach/Home-Grown-Red-Team#11]
I am having some issues with Harriet, I have read some similar issues, and supposed to be the path, but I checked and is still not working.
Thanks in advance

![image](https://github.com/assume-breach/Home-Grown-Red-Team/assets/58860205/601e9cb7-7516-4fff-88dc-25ad7697ed81)

**Comment by assume-breach** [comment]
Make sure you have run the setup.sh file. I believe this was fixed. Let me know if not.

**Comment by calex80** [comment]
Yes sir, it's working. I reinstalled and everything is fine. Thank you again

**Comment by assume-breach** [comment]
Cool. closing.
