### ISSUE TITLE
Wrong Directory And Bash File In EXE.sh

### ISSUE THREAD

**Issue by 1MinKhantSoe1** [assume-breach/Home-Grown-Red-Team#12]
In StageFright,
I just want to let you know that wrong directory and bash file in EXE.sh
![image](https://github.com/assume-breach/Home-Grown-Red-Team/assets/63970830/7274b5a0-ffe6-452e-a6bf-3e062e54f551)

It should be like this below:
![image](https://github.com/assume-breach/Home-Grown-Red-Team/assets/63970830/e9afd010-8197-4026-aa1e-0d515f020618)

Thank You !

**Comment by assume-breach** [comment]
don't now how that happened. Okay thanks! I'll fix it.

**Comment by assume-breach** [comment]
should be good now.
