### ISSUE TITLE
ubuntu version:ubuntu 20.10  or ubuntu 20.01?

### ISSUE THREAD

**Issue by hkzck** [assume-breach/Home-Grown-Red-Team#8]
I did use the ubuntu 20.10 version to run this AutoC2 on my machine, but there are some problems like dependency errors, so I want to know if the author is based on ubuntu 20.01 or ubuntu 20.10

(20.10),https://assume-breach.medium.com/home-grown-red-team-creating-a-red-development-workstation-31092d94169b
![image](https://user-images.githubusercontent.com/48936012/221787885-e6ffb703-837d-4ec9-a5c9-7ea992990c2b.png)

(20.01)https://github.com/assume-breach/Home-Grown-Red-Team/tree/main/AutoC2
![image](https://user-images.githubusercontent.com/48936012/221787749-c4e7e0da-568f-484b-9d5e-bf3aca22e242.png)

**Comment by assume-breach** [comment]
Hey it's 21.10. Most of the issues for ubuntu have gone away but I would recommend Linux Mint's latest release to avoid issues. If you wind up using a tool and it isn't installed correctly you will just need to reinstall it with the latest dependencies.
